### PR TITLE
P1 components

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
Hello everyone this PR is for just documenting all the P1 components . Please review this . Thanks all of you

### CODE REVIEW

**Review by ArjunJunna — APPROVED** [review]
just a small observation...In some documentation, at the end punctuation mark is missing. Rest everything looks good.

**Comment by Dev-AkshatGupta** [comment]
> just a small observation...In some documentation, at the end punctuation mark is missing. Rest everything looks good.

Hey thanks for review Arjun Can you please tell me what kind of punctuation marks are you talking about?

**Review by partha8 — APPROVED** [review]
LGTM! It's just at some places, in the highlightsjs container, the code is weirdly indented. 
Everything else looks good, good work.

**Comment by Dev-AkshatGupta** [comment]
> LGTM! It's just at some places, in the highlightsjs container, the code is weirdly indented. Everything else looks good, good work.

It happens because Highlight js works that way because of indentation it takes on the basis of How its indented in the code and beautify be default indent code likewise automatically though i will make it better after merging this PR Thanks for reviewing

**Pull request merged**
